from telegram import InlineKeyboardButton
from strings import (
    CREATE_PROFILE_BUTTON_LABEL, SHOW_PROFILE_BUTTON_LABEL, DELETE_PROFILE_BUTTON_LABEL,
    GENDER_MAN, GENDER_WOMAN, SKIP_BUTTON_LABEL, EDIT_PROFILE_BUTTON_LABEL, UPDATE_GOALS_BUTTON_LABEL,
    YES_BUTTON_LABEL, NO_BUTTON_LABEL,
    STATISTICS_BUTTON_LABEL, DAILY_STATISTICS_BUTTON_LABEL, LOG_WATER_BUTTON_LABEL, LOG_FOOD_BUTTON_LABEL,
    LOG_WORKOUT_BUTTON_LABEL, BACK_BUTTON_LABEL, CANCEL_BUTTON_LABEL,
    RUN_BUTTON_LABEL, CYCLE_BUTTON_LABEL, SWIM_BUTTON_LABEL, PLANK_BUTTON_LABEL, 
    GYM_BUTTON_LABEL, KLIMBING_BUTTON_LABEL
)

CREATE_PROFILE_BUTTON = [[CREATE_PROFILE_BUTTON_LABEL]]

MAIN_MENU_BUTTONS = [
    [SHOW_PROFILE_BUTTON_LABEL, UPDATE_GOALS_BUTTON_LABEL],
    [EDIT_PROFILE_BUTTON_LABEL, DELETE_PROFILE_BUTTON_LABEL],
    [STATISTICS_BUTTON_LABEL]
]

STATISTICS_MENU_BUTTONS = [
    [DAILY_STATISTICS_BUTTON_LABEL],
    [LOG_WATER_BUTTON_LABEL, LOG_FOOD_BUTTON_LABEL, LOG_WORKOUT_BUTTON_LABEL],
    [BACK_BUTTON_LABEL]
]

WORKOUT_MENU_BUTTONS = [
    [RUN_BUTTON_LABEL, CYCLE_BUTTON_LABEL, SWIM_BUTTON_LABEL],
    [GYM_BUTTON_LABEL, KLIMBING_BUTTON_LABEL, PLANK_BUTTON_LABEL],
    [BACK_BUTTON_LABEL]
]

MAN_WOMAN_INLINE_BUTTONS = [
    [
        InlineKeyboardButton(GENDER_MAN, callback_data="M"),
        InlineKeyboardButton(GENDER_WOMAN, callback_data="F")
    ]
]

SKIP_INLINE_BUTTON = [
    [
        InlineKeyboardButton(SKIP_BUTTON_LABEL, callback_data="skip")
    ]
]

YES_NO_INLINE_BUTTON = [
    [
        InlineKeyboardButton(YES_BUTTON_LABEL, callback_data="yes"),
        InlineKeyboardButton(NO_BUTTON_LABEL, callback_data="no")
    ]
]

CANCEL_BUTTON = [[CANCEL_BUTTON_LABEL]]